# docker-compose.yml

services:
  postgres:
    image: postgres:15
    container_name: raunaimer-db
    restart: always
    ports:
      - "51214:5432" 
    environment:
      POSTGRES_USER: ederraunaimer
      POSTGRES_PASSWORD: 'qbO#2(5&9<Qq'
      POSTGRES_DB: raunaimer
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: raunaimer-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

volumes:
  postgres-data:
  redis-data:
  