version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: raunaimer-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

volumes:
  redis-data:
  